Update

diff --git a/scripts/initialize_workspace b/scripts/initialize_workspace
--- a/scripts/initialize_workspace
+++ b/scripts/initialize_workspace
@@ -1,65 +1,51 @@
 #!/bin/bash -e
 
-# Get the directory of this script
-SCRIPTS_DIR=$(realpath "$(dirname "$0")")
+# get the path to this script
+SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+REPO_PATH="$( cd "$SCRIPT_DIR/.." && pwd )"
+ROOT_PATH="$( cd "$REPO_PATH/.." && pwd )"
+WORKSPACE_PATH="$ROOT_PATH/workspace"
+STUDENT_PACKAGES_PATH="$WORKSPACE_PATH/src/student-packages"
 
-# Get the absolute path to the project directory
-PROJECT_DIR=$(realpath "$SCRIPTS_DIR/..")
-CONFIG_DIR="$PROJECT_DIR/config"
+. "$SCRIPT_DIR/utils.sh"
 
-# Get the absolute path to the root directory
-ROOT_DIR=$(realpath "$PROJECT_DIR/..")
-
-# Define other directories relative to the root directory
-WORKSPACE_DIR="$ROOT_DIR/robotour-ws"
-
-# Source the utils.sh script
-. "$SCRIPTS_DIR/utils.sh"
-. "$CONFIG_DIR/config.sh"
-
-
-# Check if the user is inside the ARO singularity container
-if [ "$SINGULARITY_NAME" != "$SINGULARITY_IMAGE_NAME" ]; then
-	echo "You are not inside the RoboTour singularity container."
-	echo "Please start the singularity first using start_singularity."
+if [ "$SINGULARITY_NAME" != "robotour.simg" ]; then
+	echo "You are not inside the ARO singularity container."
+	echo "Please start the singularity first using start_singularity_aro."
 	exit 1
 fi
 
-## Create the workspace if it does not exist
-#echo "Creating workspace if it does not exist in $WORKSPACE_DIR ."
-#if [ -d "$STUDENT_PACKAGES_PATH" ]; then
-#	if ! is_online; then
-#		echo "You do not seem to be online. Not updating student packages repo."
-#	else
-#		echo "Pulling new changes into the student repo in $STUDENT_PACKAGES_PATH ."
-#		cd "$STUDENT_PACKAGES_PATH"
-#		if ! git pull; then
-#			echo "Pulling teacher changes into student repo failed. You need to resolve the merge conflicts yourself to proceed."
-#			echo "Try running the following commands:"
-#			echo "cd \"$STUDENT_PACKAGES_PATH\" && git add . && git commit -m \"My changes\" && git merge origin/master"
-#			echo "If that fails and you are unable to resolve the merge conflict, please, contact the lab teachers."
-#			exit 1
-#		fi
-#	fi
-#else
-#	mkdir -p "$STUDENT_PACKAGES_PATH/.."
-#	echo "Cloning the student repo into $STUDENT_PACKAGES_PATH . All your work on ARO will be happening there."
-#	git clone https://gitlab.fel.cvut.cz/robolab/aro/student-packages "$STUDENT_PACKAGES_PATH"
-#fi
-
-if [ ! -d "$WORKSPACE_DIR" ]; then
-  echo "Creating the workspace in $WORKSPACE_DIR ."
-  mkdir -p "$WORKSPACE_DIR/src"
+echo "Creating workspace if it does not exist in $WORKSPACE_PATH ."
+if [ -d "$STUDENT_PACKAGES_PATH" ]; then
+	if ! is_online; then
+		echo "You do not seem to be online. Not updating student packages repo."
+	else
+		echo "Pulling new changes into the student repo in $STUDENT_PACKAGES_PATH ."
+		cd "$STUDENT_PACKAGES_PATH"
+		if ! git pull; then
+			echo "Pulling teacher changes into student repo failed. You need to resolve the merge conflicts yourself to proceed."
+			echo "Try running the following commands:"
+			echo "cd \"$STUDENT_PACKAGES_PATH\" && git add . && git commit -m \"My changes\" && git merge origin/master"
+			echo "If that fails and you are unable to resolve the merge conflict, please, contact the lab teachers."
+			exit 1
+		fi
+	fi
+else
+	mkdir -p "$STUDENT_PACKAGES_PATH/.."
+	echo "Cloning the student repo into $STUDENT_PACKAGES_PATH . All your work on ARO will be happening there."
+	git clone https://gitlab.fel.cvut.cz/robolab/aro/student-packages "$STUDENT_PACKAGES_PATH"
 fi
 
-cd "$WORKSPACE_DIR"
+cd "$WORKSPACE_PATH"
 
 if [ ! -d ".catkin_tools" ]; then
 	echo "Initializing your ARO ROS workspace."
 	catkin init
+	catkin config --extend /opt/ros/aro
 fi
 
-if [ ! -d build ] || [ ! -d devel ]; then
+# TODO the check for 50.aro.sh can be removed after 2024
+if [ ! -d build ] || [ ! -d devel ] || [ ! -f devel/etc/catkin/profile.d/50.aro.sh ]; then
 	echo "Building the ARO ROS workspace."
 	catkin build
 fi
@@ -69,7 +55,6 @@ if [ ! -f "$HOME"/.tmux.conf ]; then
 	echo "set-option -g default-shell /bin/bash" > "$HOME"/.tmux.conf
 fi
 
-# Start an interactive bash while sourcing the workspace
 cd "$STUDENT_PACKAGES_PATH"
 echo "Starting interactive bash while sourcing the workspace."
 if [ $# -gt 0 ]; then
diff --git a/scripts/install_singularity b/scripts/install_singularity
--- a/scripts/install_singularity
+++ b/scripts/install_singularity
@@ -1,33 +1,53 @@
-#!/bin/bash -e
+#!/usr/bin/env bash
+set -euo pipefail  # Better error handling and exiting on error
 
-if [ -n "$SINGULARITY_NAME" ]; then
-	echo "Cannot run install_singularity from inside Singularity."
-	exit 1
-fi
+check_singularity() {
+    if [ -n "${SINGULARITY_NAME:-}" ]; then
+        echo "Cannot run install_singularity from inside Singularity."
+        exit 1
+    fi
+}
 
-if which singularity >/dev/null; then
-	echo "Singularity is already installed"
-	exit 0
-fi
+# Check if Singularity is already installed
+check_installed_singularity() {
+    if which singularity >/dev/null; then
+        echo "Singularity is already installed"
+        exit 0
+    fi
+}
 
-error_msg="Cannot automatically install Singularity on this system (only Ubuntu is supported).
-Follow the official install guide at https://apptainer.org/admin-docs/master/installation.html , 
-or you can try directly installing from the Apptainer releases page: https://github.com/apptainer/apptainer/releases ."
+# Check if Singularity CE or Apptainer is already installed via dpkg-query
+check_installed_via_dpkg() {
+    if ! which dpkg-query >/dev/null; then
+        echo -e "Cannot automatically install Singularity on this system (only Ubuntu is supported).\nFollow the official install guide at https://apptainer.org/admin-docs/master/installation.html ,\nor you can try directly installing from the Apptainer releases page: https://github.com/apptainer/apptainer/releases ."
+        exit 1
+    fi
 
-if ! which dpkg-query >/dev/null; then
-	echo -e "$error_msg"
-	exit 1
-fi
+    if [[ "$(dpkg-query --show --showformat='${db:Status-Status}\n' singularity-ce)" == "installed" ]] || [[ "$(dpkg-query --show --showformat='${db:Status-Status}\n' apptainer)" == "installed" ]]; then
+        echo "Singularity is already installed"
+        exit 0
+    fi
+}
 
-if [[ "$(dpkg-query --show --showformat='${db:Status-Status}\n' singularity-ce)" == "installed" ]] || [[ "$(dpkg-query --show --showformat='${db:Status-Status}\n' apptainer)" == "installed" ]]; then
-	echo "Singularity is already installed"
-	exit 0
-fi
+# Install Singularity via PPA
+install_singularity_via_ppa() {
+    echo "Installing Singularity. Be prepared to type your sudo password and press [Enter] for adding the PPA."
+    if (sudo add-apt-repository ppa:peci1/singularity-ce-v3 && sudo apt install singularity-ce); then
+        echo "Singularity installed"
+    else
+        echo -e "Install failed.\nCannot automatically install Singularity on this system (only Ubuntu is supported).\nFollow the official install guide at https://apptainer.org/admin-docs/master/installation.html ,\nor you can try directly installing from the Apptainer releases page: https://github.com/apptainer/apptainer/releases ."
+        exit 1
+    fi
+}
 
-echo "Installing Singularity. Be prepared to type your sudo password and press [Enter] for adding the PPA."
-if (sudo add-apt-repository ppa:peci1/singularity-ce-v3 && sudo apt install singularity-ce); then
-	echo "Singularity installed"
-else
-	echo -e "Install failed.\n$error_msg"
-	exit 1
-fi
+# Main function to execute all necessary steps
+main() {
+    check_singularity
+    check_installed_singularity
+    check_installed_via_dpkg
+    install_singularity_via_ppa
+}
+
+# Execute main function
+main
+
diff --git a/scripts/setup_catkin_workspace b/scripts/setup_catkin_workspace
--- a/scripts/setup_catkin_workspace
+++ b/scripts/setup_catkin_workspace
@@ -1,103 +1,123 @@
-#!/bin/bash
-set -e
-dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+#!/usr/bin/env bash
+set -euo pipefail  # Better error handling and exiting on error
 
-usage="Setup robolab catkin workspace at specified directory.
+# Function to print usage information
+print_usage() {
+    cat <<EOF
+Setup Catkin workspace at specified directory.
 
 Usage:
     setup_catkin_workspace [<workspace>]
 
-Options (environmental variables):
-- extend:       Workspace to extend.
-- ros:          ROS distribution (kinetic/melodic).
-- rosdep:       Install dependencies via rosdep? [y/n]
-- rosinstall:   Workspace rosinstall files.
-- install:      Path to install space. Don't install if not provided.
-"
+Options:
+- -e|--extend:       Workspace to extend.
+- -r|--ros:          ROS distribution (kinetic/melodic/noetic).
+- -d|--rosdep:       Install dependencies via rosdep? [y/n]
+- -i|--rosinstall:   Workspace rosinstall files.
+- -p|--install:      Path to install space. Don't install if not provided.
+EOF
+}
 
-# Parse arguments.
-if [ "$#" -gt 1 ]; then
-    echo 'ERROR: Invalid number of arguments.'
-    echo
-    echo "${usage}"
+# Function to handle errors and exit
+handle_error() {
+    echo "ERROR: $1" >&2
     exit 1
-fi
+}
 
-# Workspace
-if [ "$#" -eq 1 ]; then
-    ws="$1"
-fi
-if [ ! "${ws}" ]; then
-    ws="$(pwd)"
-fi
-if [ ! "${ws}" ]; then
-    echo 'ERROR: Workspace not specified.'
-    exit 2
-fi
-ws=$(realpath "${ws}")
-echo "Workspace: ${ws}"
+# Function to configure main repositories from provided rosinstall files
+configure_repositories() {
+    mkdir -p "${workspace}/src"
+    cd "${workspace}/src" || handle_error "Failed to navigate to ${workspace}/src"
+    wstool init
 
-# ROS distribution
-if [ ! "${ros}" ] && [ -d /opt/ros/melodic ]; then
-    ros=melodic
-fi
-if [ ! "${ros}" ] && [ -d /opt/ros/kinetic ]; then
-    ros=kinetic
-fi
-if [ ! "${ros}" ]; then
-    echo 'ERROR: No ROS distribution found.'
-    exit 3
-fi
-echo "ROS distribution: ${ros}"
-
-# Extended workspace
-if [ ! "${extend}" ]; then
-    extend=/opt/ros/$ros
-fi
-extend=$(realpath "${extend}")
-if [ ! "${extend}" ]; then
-    echo 'ERROR: Extended workspace not specified.'
-    exit 4
-fi
-echo "Extended workspace: ${extend}"
-
-# Workspace rosinstall files
-if [ ! "${rosinstall}" ]; then
-    rosinstall="${dir}/../config/robolab.rosinstall ${dir}/../config/robolab_${ros}.rosinstall"
-fi
-if [ ! "${rosinstall}" ]; then
-    echo 'ERROR: Workspace configuration rosinstall files not specified.'
-    exit 5
-fi
-echo "Workspace rosinstall files: ${rosinstall}"
-
-# Configure main repositories from provided rosinstall files.
-mkdir -p "${ws}/src"
-cd "${ws}/src"
-wstool init
-# Keep first entry with given key (-k).
-# Make sure there are no duplicates in these curated lists.
-for f in ${rosinstall}; do
-    wstool merge -k ${f}
+    # Merge provided rosinstall files
+    for file in "${rosinstall[@]}"; do
+        [ -e "$file" ] && wstool merge -k "$file"
+    done
     wstool up -j 8
-done
+}
 
-# Install rosdep dependencies.
-if [ "${rosdep}" = "y" ]; then
-    cd "${ws}"
-    rosdep update
-    rosdep install --from-paths src --ignore-src --rosdistro ${ros} -r -y
-fi
+# Function to install ROS dependencies using rosdep
+install_ros_dependencies() {
+    if [ "${rosdep}" = "y" ]; then
+        rosdep update
+        rosdep install --from-paths "${workspace}/src" --ignore-src --rosdistro "${ros}" -r -y
+    fi
+}
 
-# Initialize, configure, and build catkin workspace.
-cd "${ws}"
-catkin init
-catkin config --extend "${extend}"
-catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release
-if [ "${install}" ]; then
-    catkin config -i "${install}" --install
-fi
-if ! catkin build -c; then
-    echo 'ERROR: Catkin build incomplete!'
-    exit 1
-fi
+# Function to initialize, configure, and build catkin workspace
+initialize_catkin_workspace() {
+    cd "${workspace}" || handle_error "Failed to navigate to ${workspace}"
+    catkin init
+    catkin config --extend "${extend}"
+    catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release
+    [ -n "${install}" ] && catkin config -i "${install}" --install
+    catkin build -c || handle_error "Catkin build incomplete"
+}
+
+# Main script logic
+main() {
+    # Parse arguments
+    while [[ $# -gt 0 ]]; do
+        key="$1"
+        case $key in
+            -e|--extend)
+            extend="$2"
+            shift # past argument
+            shift # past value
+            ;;
+            -r|--ros)
+            ros="$2"
+            shift # past argument
+            shift # past value
+            ;;
+            -d|--rosdep)
+            rosdep="$2"
+            shift # past argument
+            shift # past value
+            ;;
+            -i|--rosinstall)
+            rosinstall+=("$2")
+            shift # past argument
+            shift # past value
+            ;;
+            -p|--install)
+            install="$2"
+            shift # past argument
+            shift # past value
+            ;;
+            *)
+            print_usage
+            handle_error "Unknown option: $1"
+            ;;
+        esac
+    done
+    workspace="${1:-$(pwd)}"  # Default to current directory if workspace not provided
+
+    echo "=================================================="
+    echo "Setting up Catkin workspace at: ${workspace}"
+    echo "=================================================="
+
+    echo "ROS distribution: ${ros}"
+    echo "Extend workspace: ${extend}"
+    echo "Install space: ${install}"
+    echo "Install dependencies: ${rosdep}"
+    echo "ROS install files: ${rosinstall[*]}"
+    echo "=================================================="
+
+    # Validate required arguments
+    if [[ -z "${ros}" ]]; then
+        handle_error "ROS distribution not provided."
+    fi
+
+    # Determine extended workspace
+    extend="${extend:-/opt/ros/${ros}}"
+
+    # Configure repositories, install dependencies, and initialize catkin workspace
+    configure_repositories
+    install_ros_dependencies
+    initialize_catkin_workspace
+}
+
+# Execute main function with arguments passed to the script
+main "$@"
diff --git a/scripts/start_singularity b/scripts/start_singularity
--- a/scripts/start_singularity
+++ b/scripts/start_singularity
@@ -1,65 +1,83 @@
-#!/bin/bash -e
+#!/usr/bin/env bash
+set -eo pipefail  # Better error handling and exiting on error
 
-# get the path to this script
-SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
-REPO_PATH="$(cd "$SCRIPT_DIR/.." && pwd)"
-ROOT_PATH="$(cd "$REPO_PATH/.." && pwd)"
+SCRIPTS_PATH=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
+PROJECT_PATH=$(realpath "$SCRIPTS_PATH/..")
+ROOT_PATH=$(realpath "$PROJECT_PATH/..")
 
-. "$SCRIPT_DIR/utils.sh"
+source "$SCRIPTS_PATH/utils.sh"
 
-IS_TURTLE_OR_LAB_DESKTOP=0
-IMAGE="$REPO_PATH/images/robotour.simg"
+IMAGE_NAME="robotour.simg"
+IMAGE_PATH="${PROJECT_PATH}/images/${IMAGE_NAME}"
 
-# Try to mount /local directory on lab PCs and robots if not already mounted
-[ -d /local ] && findmnt --fstab /local >/dev/null && ! findmnt -M /local >/dev/null && mount /local >/dev/null
-if [ -f /local/robolab_noetic.simg ]; then
-	IS_TURTLE_OR_LAB_DESKTOP=1
-	IMAGE=/local/robolab_noetic.simg
-fi
+ENV_VARIABLES=(
+    ROS_MASTER_URI
+    ROS_HOSTNAME
+    ROS_IP
+    ROS_HOME
+    ROS_LOG_DIR
+    ROSCONSOLE_CONFIG_FILE
+    ROS_PYTHON_LOG_CONFIG_FILE
+    HOSTNAME
+    DISPLAY
+    USER
+    XAUTHORITY
+    LANG
+    DBUS_SESSION_BUS_ADDRESS
+)
 
-if is_online; then
-	echo "Updating repository"
-	(cd "$REPO_PATH" && git pull)
-fi
+update_repository() {
+    if is_online; then
+        echo "Updating repository"
+        (cd "$PROJECT_PATH" && git pull)
+    fi
+}
 
 # If you have NVidia GPU and rendering acceleration doesn't work for you, call `export ARO_SINGULARITY_NV=1` before
 # launching this script. However, this only works on Ubuntu 20.04 and older systems.
-nv=""
-[ "$ARO_SINGULARITY_NV" = "1" ] && nv="--nv"
+set_nvidia_gpu() {
+    nv=""
+    if [ "$ARO_SINGULARITY_NV" = "1" ]; then
+        echo "Setting up NVidia GPU support."
+        nv="--nv"
+    fi
+}
 
-if [ "$SINGULARITY_NAME" = "robotour.simg" ]; then
-	echo "You can not start new singularity container from within another singularity container."
-	echo "Initializing ARO workspace within current session instead."
-	"$SCRIPT_DIR"/initialize_workspace "$@"
-else
-	# If the computer is online, try to update the image (but not on lab machines, their update mechanism is different).
-  #	[ "$IS_TURTLE_OR_LAB_DESKTOP" = "0" ] && is_online && "$SCRIPT_DIR"/download_singularity_image
+bind_directories() {
+    bind="${ROOT_PATH}:${ROOT_PATH}"
+    if [ -d /snap ]; then
+      echo "Mounting /snap directory."
+      bind="${bind},/snap:/snap"
+    fi
+}
 
-	# Check whether singularity is installed.
-	"$SCRIPT_DIR"/install_singularity
+main() {
+    # Accept argument -u or --update to update the image
+    if [ "${1:-}" = "-u" ] || [ "${1:-}" = "--update" ]; then
+      echo "Updating the image."
+      is_online && "$SCRIPTS_PATH"/download_singularity_image
+    fi
 
-  . "$SCRIPT_DIR/utils.sh"
+    # If in singularity container exit
+    in_singularity && echo "You are already inside a singularity container." && exit 1
 
-  # Set the PS1 prompt
-  export SINGULARITYENV_PS1="${IN_NIX_SHELL:+[nix-shell:${IN_NIX_SHELL}] }"'\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[1;33m\]$(parse_git_branch)$(detect_singularity) \[\033[01;34m\]\$\[\033[00m\] '
+    # Check whether singularity is installed and install it if not
+    "${SCRIPTS_PATH}"/install_singularity
 
-	# Only these environment variables will be passed to the container. This prevents clobbering of PYTHONPATH etc.
-  export SINGULARITYENV_PS1="\[\033[01;32m\]\u@\h\[\033[00m\]\[\e[33m\][AROSingularity]\[\e[0m\]:\[\033[01;34m\]\w\[\033[00m\]$ "
-	[ -n "$ROS_MASTER_URI" ] && export SINGULARITYENV_ROS_MASTER_URI="$ROS_MASTER_URI"
-	[ -n "$ROS_HOSTNAME" ] && export SINGULARITYENV_ROS_HOSTNAME="$ROS_HOSTNAME"
-	[ -n "$ROS_IP" ] && export SINGULARITYENV_ROS_IP="$ROS_IP"
-	[ -n "$ROS_HOME" ] && export SINGULARITYENV_ROS_HOME="$ROS_HOME"
-	[ -n "$ROS_LOG_DIR" ] && export SINGULARITYENV_ROS_LOG_DIR="$ROS_LOG_DIR"
-	[ -n "$ROSCONSOLE_CONFIG_FILE" ] && export SINGULARITYENV_ROSCONSOLE_CONFIG_FILE="$ROSCONSOLE_CONFIG_FILE"
-	[ -n "$ROS_PYTHON_LOG_CONFIG_FILE" ] && export SINGULARITYENV_ROS_PYTHON_LOG_CONFIG_FILE="$ROS_PYTHON_LOG_CONFIG_FILE"
-	[ -n "$HOSTNAME" ] && export SINGULARITYENV_HOSTNAME="$HOSTNAME"
-	[ -n "$DISPLAY" ] && export SINGULARITYENV_DISPLAY="$DISPLAY"
-	[ -n "$USER" ] && export SINGULARITYENV_USER="$USER"
-	[ -n "$XAUTHORITY" ] && export SINGULARITYENV_XAUTHORITY="$XAUTHORITY"
-	[ -n "$LANG" ] && export SINGULARITYENV_LANG="$LANG"
-	[ -n "$DBUS_SESSION_BUS_ADDRESS" ] && export SINGULARITYENV_DBUS_SESSION_BUS_ADDRESS="$DBUS_SESSION_BUS_ADDRESS"
+    update_repository
 
-	echo "Starting Singularity container from image $IMAGE ."
-	singularity exec $nv --bind /snap:/snap -e -B "$ROOT_PATH" "$IMAGE" "$SCRIPT_DIR/initialize_workspace" "$@"
-fi
+    bind_directories
+    set_nvidia_gpu
 
+    export PS1="\[\033[01;32m\]\u@\h\[\033[00m\]\[\e[33m\] [RoboTour] \[\e[0m\]:\[\033[01;34m\]\w\[\033[00m\]$ "
+
+    for var_name in "${ENV_VARIABLES[@]}"; do
+        export_environment_variable_if_present "$var_name"
+    done
+
+    echo "Starting Singularity container from image ${IMAGE_PATH}."
+    singularity exec -e -B "${ROOT_PATH}" "${IMAGE_PATH}" "${SCRIPTS_PATH}/initialize_workspace" "$@"
+}
+
+# Execute main function
+main "$@"
